# Development override for docker-compose
# Use with: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

version: '3.8'

services:
  bricks-manager:
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - FLASK_RUN_RELOAD=1
    volumes:
      # Mount source code for live reloading in development
      - ./brick_manager:/app/brick_manager:ro
    command: >
      sh -c "cd /app/brick_manager && 
             python -m flask run --host=0.0.0.0 --port=5000 --reload"
    ports:
      - "5000:5000"
      - "5001:5001"  # Additional port for debugging if needed

  # Disable nginx in development
  nginx:
    profiles:
      - disabled